MediXpert/MediX/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('patient/', include('patient.urls', namespace="patient")),
    path('doctor/', include('doctor.urls', namespace="doctor")),
    path('lab/', include('lab.urls', namespace="lab")),

]

MediXpert/doctor/urls.py
from django.urls import path
from . import views

app_name = "patient"

urlpatterns=[
    path('home/', views.home, name='home'),
    path('logout/', views.logout_user, name='logout'),
    path('viewpatients/', views.viewPatients, name='viewpatients'),
    path('refer/', views.refer, name='refer'),
    path('stopconsult/<int:id>', views.stopConsult, name='stopconsult'),
    path('diagnose', views.diagnose, name='diagnose'),
    path('predict/<int:id>', views.predict, name='predict'),
    path('model/<int:id>', views.model, name='model'),
]

MediXpert/lab/urls.py
from django.urls import path
from . import views

app_name = "patient"

urlpatterns=[
    path('home/', views.home, name='home'),
    path('logout/', views.logout_user, name='logout'),
    path('consult/<int:id>/', views.consult, name='consult'),
    path('addDetails/', views.addDetails, name='addDetails'),
]

MediXpert/patient/urls.py
from django.urls import path
from . import views

app_name = "patient"

urlpatterns=[
    path('home/', views.home, name='home'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.create_user, name='register'),

    path('doctor/', views.doctorList, name='doctor'),
    # path('doctorbook/<int:id>/', views.doctorBook, name='doctorbook'),
    path('doctorbook/', views.doctorList, name='doctorbook'),
    path('bookdoctor/<int:id>', views.doctorBook, name='bookdoctor'),
    path('appointment/', views.appointment, name='appointment'),
    path('profile/', views.profile, name='profile'),
    path('user/', views.user, name='user'),
    path('report/<int:id>', views.report, name='report'),
]

MediXpert/doctor/models.py
from django.db import models

# Create your models here.

MediXpert/patient/models.py
from datetime import datetime
from django.db import models


class Patient(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=30)
    phone_num = models.IntegerField(default=0)
    email = models.CharField(max_length=30)
    password = models.CharField(max_length=50)
    role = models.CharField(max_length=30, default='patient')

    def __str__(self):
        return self.username


class LabAssist(models.Model):
    full_name = models.CharField(max_length=30)
    email = models.CharField(max_length=30)
    password = models.CharField(max_length=50)
    role = models.CharField(max_length=30, default='lab')

    def __str__(self):
        return self.full_name


class Doctor(models.Model):
    id = models.AutoField(primary_key=True)
    full_name = models.CharField(max_length=30)
    desig = models.CharField(max_length=30)
    email = models.CharField(max_length=30)
    password = models.CharField(max_length=50)
    role = models.CharField(max_length=30, default='doc')

    def __str__(self):
        return self.full_name


class DBook(models.Model):
    id = models.AutoField(primary_key=True)
    uname = models.CharField(max_length=30)
    uid = models.IntegerField()
    dname = models.CharField(max_length=30)
    age = models.CharField(max_length=30)
    gender = models.CharField(max_length=30)
    bdate = models.DateField()
    btime = models.CharField(max_length=30)
    refer = models.BooleanField(default=True)
    status = models.BooleanField(default=True)


class DBookFinish(models.Model):
    bid = models.IntegerField()
    uname = models.CharField(max_length=30)
    uid = models.IntegerField()
    dname = models.CharField(max_length=30)
    age = models.CharField(max_length=30)
    gender = models.CharField(max_length=30)
    bdate = models.DateField()
    btime = models.CharField(max_length=30)
    refer = models.BooleanField(default=True)
    status = models.BooleanField(default=True)


class testResult(models.Model):
    tid = models.AutoField(primary_key=True)
    uname = models.CharField(max_length=30)
    uid = models.IntegerField()
    bid = models.IntegerField()
    age = models.CharField(max_length=30)
    gender = models.CharField(max_length=30)
    bloodp = models.IntegerField(default=0)
    chol = models.IntegerField(default=0)
    fasting = models.CharField(max_length=30,default="NULL")
    ecg = models.CharField(max_length=100,default="NULL")
    heart = models.IntegerField(default=0)
    cpain = models.CharField(max_length=30,default="NULL")
    cpaintype = models.CharField(max_length=200,default="NULL")
    status = models.BooleanField(default=True)

MediXpert/patient/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100, min_length=2,
                               widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Enter your name'}))
    phone = forms.CharField(label='Phone number', max_length=35, min_length=10,
                             widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Enter Mobile No.'}))
    email = forms.EmailField(label='Email', max_length=35, min_length=5,
                             widget=forms.EmailInput(attrs={'class': 'form-control','placeholder': 'Enter Email ID'}))
    password1 = forms.CharField(label='Password', max_length=50, min_length=5,
                                widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'New Password'}))
    password2 = forms.CharField(label='Confirm Password',
                                max_length=50, min_length=5,
                                widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'Confirm Password'}))

MediXpert/doctor/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponse
from patient.models import *
from .models import *
from sklearn.preprocessing import MinMaxScaler
import joblib
import os
import numpy as np
import pickle
import csv
from datetime import datetime
from django.utils import timezone

# Create your views here.

def home(request):
    return render(request,'dhome.html')

def logout_user(request):
    logout(request)
    return redirect('index')

def diagnose(request):
    name = request.user.get_short_name()
    patients = DBook.objects.all().filter(dname=name)  
    return render(request, 'diagnose.html', {"patients":patients})

def viewPatients(request):
    name = request.user.get_short_name()
    patients = DBook.objects.all().filter(dname=name)  
    return render(request, 'patients.html', {"patients":patients})

def refer(request):
    if request.method == "POST":
        uname = request.POST['uname']
        uid = request.POST['uid']
        age = request.POST['age']
        gender = request.POST['gender']
        id = request.POST['bid']

        post=testResult()
        post.uname = uname
        post.uid = uid
        post.bid = id
        post.age = age
        post.gender = gender
        post.save()

        dname = request.user.get_short_name()
        book = get_object_or_404(DBook, id=id)
        book.refer = False
        book.save()

        return redirect('doctor:viewpatients')
    else:
        return redirect('doctor:viewpatients')


def stopConsult(request, id):
    dname = request.user.get_short_name()
    book = get_object_or_404(DBook, id=id)
    book.status = False
    book.save()
    doc = request.user.get_short_name()
    records = DBook.objects.all().filter(id=id)
    for record in records:
        DBookFinish.objects.create(
            bid=record.id,
            uname=record.uname,
            dname=record.dname,
            age=record.age,
            gender=record.gender,
            bdate=record.bdate,
            btime=record.btime,
            uid=record.uid,
            refer=record.refer,
            status=record.status
        )

        # Retrieve a record
        # rec = DBook.objects.get(dname=doc)
        DBook.objects.filter(id=id).delete()

        # Delete the record
        # rec.delete()
        return redirect('doctor:diagnose')


def predict(request, id):
    books = get_object_or_404(testResult, bid=id)
    records = testResult.objects.all().filter(bid=id)
    if books.status == False:
        return render(request,'predict.html', {"records":records, "books":books}) # Lab report added
    else:
        messages.error(request, "Lab report not available!!!")
        return redirect('doctor:diagnose') # Lab report not added


def model(request, id):
    b = get_object_or_404(testResult, bid=id)
    age = b.age
    sex = b.gender
    trestbps = b.bloodp
    chol = b.chol
    restecg = b.ecg
    thalach = b.heart
    exang = b.cpain
    cp = b.cpaintype
    fbs = b.fasting
    x = np.array([age, sex, cp, trestbps, chol, fbs, restecg,
                  thalach, exang]).reshape(1, -1)

    scaler_path = os.path.join('static\models\scaler.pkl')

    scaler = None

    with open(scaler_path, 'rb') as f:
        scaler = pickle.load(f)

    x = scaler.transform(x)

    model_path = os.path.join('static\\models\\rfc.sav')
    clf = joblib.load(model_path)

    y = clf.predict(x)
   
    return render(request,'predict.html', {'y':int(y)})



    

MediXpert/patient/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from .forms import UserRegistrationForm
from django.contrib import messages
from django.http import HttpResponse
from .models import *
from django.db.models import Q
from datetime import datetime
from django.utils import timezone
from django.core.mail import send_mail


def home(request):
    doctors = Doctor.objects.all()
    return render(request, 'home.html', {'doctors':doctors})
    # return render(request,'home.html')

def doctor_details(request):
    return render(request,'doctors.html')

def login_user(request):
    try:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(username=username, password=password)
            if user.check_password("Doc@1234"):
                login(request, user)
                redirect_url = request.GET.get('next', 'doctor:home')
                return redirect(redirect_url)
            elif user.check_password("Doc2@1234"):
                login(request, user)
                redirect_url = request.GET.get('next', 'doctor:home')
                return redirect(redirect_url)
            elif user.check_password("Lab@1234"):
                login(request, user)
                redirect_url = request.GET.get('next', 'lab:home')
                return redirect(redirect_url)
            elif user is not None:
                login(request, user)
                redirect_url = request.GET.get('next', 'patient:home')
                return redirect(redirect_url)
            else:
                messages.warning(request, "Incorrect Username/Password!")
                return render(request, 'login.html')

    except AttributeError:
        messages.warning(request, "Incorrect Username/Password!")
        return render(request, 'login.html')
    return render(request, 'login.html')


def logout_user(request):
    logout(request)
    return redirect('index')


def create_user(request):
    if request.method == 'POST':
        check1 = False
        check2 = False
        check3 = False
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']
            email = form.cleaned_data['email']

            if password1 != password2:
                check1 = True
                messages.error(request, 'Password did not match!',
                               extra_tags='alert alert-warning alert-dismissible fade show')
            if User.objects.filter(username=username).exists():
                check2 = True
                messages.error(request, 'Username already exists!',
                               extra_tags='alert alert-warning alert-dismissible fade show')
            if User.objects.filter(email=email).exists():
                check3 = True
                messages.error(request, 'Email already registered!',
                               extra_tags='alert alert-warning alert-dismissible fade show')

            if check1 or check2 or check3:
                messages.error(
                    request, "Registration Failed!", extra_tags='alert alert-warning alert-dismissible fade show')
                return redirect('patient:register')
            else:
                user = User.objects.create_user(
                    username=username, password=password1, email=email)
                messages.success(
                    request, f'Thanks for registering {user.username}.', extra_tags='alert alert-success alert-dismissible fade show')
                acc=Patient()
                acc.username = form.cleaned_data['username']
                acc.phone_num = form.cleaned_data['phone']
                acc.email = form.cleaned_data['email']
                acc.password= form.cleaned_data['password1']

                acc.save()
                print("user_created")
                return redirect('patient:login')
    else:
        form = UserRegistrationForm()
    return render(request, 'reg.html', {'form': form})


def profile(request):  
    name = request.user
    appoints = DBook.objects.all().filter(uname=name,  status=1)  
    pastappoints = DBookFinish.objects.all().filter(uname=name,  status=0) 
    # stat=pastappoints.status
    # if stat == 0:
    #     stat = "Consultation successfll"
    # else:
    #     stat = "Consultation successfll"
    return render(request, 'profile.html', {"appoints":appoints, "pastappoints":pastappoints})

def user(request):  
    name = request.user
    user = User.objects.all().filter(username=name)  
    d = request.user.date_joined
    dt = datetime(2022, 12, 21, 12, 34, 56)
    date = dt.date()
    return render(request, 'user.html', {"user":user,"date":date})


def doctorList(request):        
    doctors = Doctor.objects.all()
    return render(request, 'doctors.html', {'doctors':doctors})

def report(request, id):    
    name = request.user
    reports = testResult.objects.all().filter(bid=id)  
    return render(request, 'report.html', {'reports':reports})


def doctorBook(request,id):    
    uname = request.user
    iid = request.user.id
    doctors = get_object_or_404(Doctor, pk=id)
    return render(request, 'doctorbook.html', {"doctors":doctors,"name":uname, "iid":iid})

def appointment(request):
    uname = request.user
    docname = request.POST['dname']
    user = User.objects.all().filter(username=uname)  
    uemail = request.user.email
    doctors = get_object_or_404(Doctor, full_name=docname)
    if request.method == "POST":
        uuid = request.user.id
        doc = request.POST['dname']
        bdat = request.POST['date']
        time = request.POST['time']

        date_string = bdat
        date_format = "%Y-%m-%d"
        date = datetime.strptime(date_string, date_format)
        date = timezone.make_aware(date)

        appointments_on_date = DBook.objects.filter(dname=doc, bdate=date, btime=time)

        if appointments_on_date.exists():
            print("appointment already there")
            
            messages.error(request, "Doctor not available !!!")
            messages.error(request, "Select a different date/time")
            # return redirect('patient:doctorbook')
            return render(request, 'doctorbook.html', {"doctors":doctors,"name":uname,"iid":uuid})
        else:
            post=DBook()
            post.uname = request.POST['pname']
            post.dname = request.POST['dname']
            post.age = request.POST['age']
            post.gender = request.POST['inlineRadioOptions']
            post.bdate = request.POST['date']
            post.btime = request.POST['time']
            post.uid = request.POST['iid']
            post.save()
            messages.success(request, "Appointment has taken")

            usname = str(uname)
            subject = "Appointment Confirmation MediXpert"
            message = "Hi, "+usname+",   You recently scheduled an appointment for "+bdat+" at "+time+". The appointment has been confirmed successfully. Please reply to this email if you’d like to cancel or reschedule the appointment."

            # send_mail(subject, message, 'sr.mca2123@saintgits.org', [uemail], fail_silently=False)

            return render(request, 'home.html')
    else:
        return redirect('patient:doctorbook')

MediXpert/templates/doctors.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="">

  <title> Orthoc </title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
  <style>
    .container {
  border-radius: 40px;
}
  </style>
</head>

<body class="sub_page">

  <div class="hero_area">

    <div class="hero_bg_box">
      <img src="{% static 'images/hero-bg.png' %}" alt="">
    </div>

    <!-- header section strats -->
    <header class="header_section">
      <div class="container">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="{% url 'patient:home' %}">
            <span>
              MediXpert
            </span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'patient:home' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'patient:doctor' %}">Doctors</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'patient:profile' %}">Appointments</a>
              </li>
              <li class="nav-item">
                <!-- <a class="nav-link" href="{% url 'patient:profile' %}">{{ request.user.username }}</a>  -->
                <a class="nav-link" href="{% url 'patient:user' %}">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" onclick="if (confirm('Are you sure you want to log out?')) { } else { event.preventDefault(); }" href="{% url 'patient:logout' %}">Logout</a>
              </li>
              <form class="form-inline">
                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                  <i class="fa fa-search" aria-hidden="true"></i>
                </button>
              </form>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
  </div>

  <!-- doctor section -->

  <section class="doctor_section layout_padding">
    <div class="container" style="background-color: rgb(0, 103, 69);">
      <br>
              <!-- breadcrumb section -->
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb" style="background-color: rgb(0, 103, 69);">
                  <li class="breadcrumb-item active"><a href="{% url 'patient:home' %}" style="color: rgb(149, 147, 147);">Home</a></li>
                  <li class="breadcrumb-item" aria-current="page" style="color: rgb(255, 255, 255);">Doctors</li>
                </ol>
              </nav>
              <!-- end breadcrumb section -->
      <div class="heading_container heading_center">
        <h2>
          Our Doctors
        </h2>
      </div>
<!-- 
      {% if messages %}
      <ul class="messages-2">
        {% for message in messages %}
            {% if message.tags == "error" %}
            <script>
              alert('Unsuccessfull!!!. Doctor not available!!!');
            </script>
            {% endif %}
        {% endfor %}
    </ul>
        {% endif %} -->

        
      <div class="row">
        {% for doctor in doctors %}
        <div class="col-sm-6 col-lg-4 mx-auto">
          <div class="box">
            <div class="img-box">
              <img src="{% static 'images/d2.png' %}" alt="">
            </div>
            <div class="detail-box">
              <div class="social_box">
                <a class="btn btn-info" href="{% url 'patient:bookdoctor' doctor.id %}" role="button">Select</a>
              </div>
              <h5>
                {{ doctor.full_name }}
              </h5>
              <h6 class="">
                {{ doctor.desig }}
              </h6>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <!-- <div class="btn-box">
        <a href="">
          View All
        </a>
      </div> -->
      <br><br>
    </div>
  </section>

  <!-- end doctor section -->

  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-3 footer_col">
          <div class="footer_contact">
            <h4>
        
            </h4>
  
          </div>

        </div>
        <div class="col-md-6 col-lg-3 footer_col">
          <div class="footer_detail">
            <h4>
        
            </h4>
            <p>
             
            </p>
          </div>
        </div>
        <div class="col-md-6 col-lg-2 mx-auto footer_col">
          <div class="footer_link_box">
            <h4>
         
            </h4>
            <div class="footer_links">
              <a class="" href="index.html">
               
              </a>
              <a class="" href="about.html">
              
              </a>
              <a class="" href="departments.html">
           
              </a>
              <a class="active" href="doctors.html">
              
              </a>
              <a class="" href="contact.html">
              
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 footer_col ">
          <h4>
       
          </h4>
          <form action="#">
      
            
  
          </form>
        </div>
      </div>
      <div class="footer-info">
        <p>
       
        </p>
      </div>
    </div>
  </footer>
  <!-- footer section -->

  <!-- jQery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
  <!-- owl slider -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- custom js -->
  <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
  </script>
  <!-- End Google Map -->

</body>

</html>

MediXpert/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>test</title>
    <link rel="stylesheet" href="{% static 'css/logstyle.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  </head>
  <body>
<!--Hey! This is the original version
of Simple CSS Waves-->

<div class="header">
  <!-- {% if messages %}
        {% for message in messages %}
            {% if message.tags == "warning" %}
            <script>
              alert('Login Unsuccessfull!!!. Please check Username/Password');
            </script>
            {% endif %}
        {% endfor %}
    {% endif %} -->

    <!--Content before waves-->
    <div class="inner-header flex">
      <!--Just the logo.. Don't mind this-->
      <div class="center">
        <h1>Login</h1>
        <form method="post">
          {% csrf_token %}

          {% if messages %}
          <div class="show">
              {% for message in messages %}
              <div class="alert alert-success" role="alert">
                <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
              </div>
              {% endfor %}
            </div> 
              {% endif %}


          <div class="txt_field">
            <input type="text" name="username" required>
            <span></span>
            <label>Username</label>
          </div>
          <div class="txt_field">
            <input type="password" name="password" required>
            <span></span>
            <label>Password</label>
          </div>
          <div class="pass">Forgot Password?</div>
          <input type="submit" value="Login">
          <div class="signup_link">
            Not a member? <a href="{% url 'patient:register' %}">Signup</a>
          </div>
        </form>
      </div>
    </div>
  
    <!--Waves Container-->
    <div>
      <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
        <defs>
          <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
        </defs>
        <g class="parallax">
          <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(255,255,255,0.7" />
          <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.5)" />
          <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.3)" />
          <use xlink:href="#gentle-wave" x="48" y="7" fill="#fff" />
        </g>
      </svg>
    </div>
    <!--Waves end-->
  
  </div>
  <!--Header ends-->
  <script>
    setTimeout(function() {
      var errorMessages = document.querySelectorAll('.show');
        for (var i = 0; i < errorMessages.length; i++) {
            errorMessages[i].remove();
        }
    }, 5000);
</script>
 
</body>
</html>

MediXpert/templates/reg.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>test</title>
    <link rel="stylesheet" href="{% static 'css/logstyle.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  </head>
  <body>
<!--Hey! This is the original version
of Simple CSS Waves-->

<div class="header">

    <!--Content before waves-->
    <div class="inner-header2 flex2">
      <!--Just the logo.. Don't mind this-->
      <div style="margin-top: 100px;" class="wrapper">
    <h2>Registration</h2>

    <div class="show">
      {% if messages %}
        {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
      </ul>
        {% endif %}
    </div>


    <form action="" method="POST">
      {% csrf_token %}
      <div class="input-box">
        {{ form.username }}
      </div>
      <div class="input-box">
        {{ form.phone }}
      </div>
      <div class="input-box">
        {{ form.email }}
      </div>
      <div class="input-box">
        {{ form.password1 }}
      </div>
      <div class="input-box">
        {{ form.password2 }}
      </div>
      <input type="submit" value="Sign UP">
      <div class="signup_link">
      Already have an account? <a href="{% url 'patient:login' %}">Login Here</a>
    </div>    
  </form>
  </div>
    </div>
  
    <!--Waves Container-->
    <div>
      <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
        <defs>
          <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
        </defs>
        <g class="parallax">
          <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(255,255,255,0.7" />
          <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.5)" />
          <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.3)" />
          <use xlink:href="#gentle-wave" x="48" y="7" fill="#fff" />
        </g>
      </svg>
    </div>
    <!--Waves end-->
  
  </div>
  <!--Header ends-->

  <script>
    setTimeout(function() {
      var errorMessages = document.querySelectorAll('.show');
        for (var i = 0; i < errorMessages.length; i++) {
            errorMessages[i].remove();
        }
    }, 2000);
</script>
  
 
</body>
</html>